feat(platform): update client go to 1.24
tkestack/tke pull request #2237
Opened 2023-02-23 01:07 UTC by leoryu

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2023-03-16 07:18 UTC, leoryu commented on pkg/application/controller/app/app_controller.go
> -		newStatus.Phase = applicationv1.AppPhaseInstalling
恢复原样

2023-03-16 07:19 UTC, leoryu commented on pkg/application/controller/app/app_controller.go
> +	if app.Status.Phase == applicationv1.AppPhaseSucceeded && hasSynced(app) {
恢复原样

2023-03-16 07:20 UTC, leoryu commented on pkg/application/helm/action/client.go
> +	err := actionConfig.Init(c.restClientGetter, namespace, c.helmDriver, log.Debugf)
@GaoXiaodong check

2023-03-16 07:21 UTC, leoryu commented on pkg/application/helm/action/install.go
> +				log.Infof("Release %s is already exist. igonre it now.", options.ReleaseName)
恢复原样

2023-03-16 07:35 UTC, leoryu commented on pkg/platform/util/workqueue/priority_queue.go
> +	return q.processing.len() != 0
@277631272

2023-03-16 07:35 UTC, leoryu commented on pkg/platform/util/workqueue/priority_queue.go
> +	return q.processing.len() != 0
@277631272

2023-03-17 05:33 UTC, willzgli requested changes

2023-03-17 08:25 UTC, GaoXiaodong commented on pkg/application/helm/action/client.go
> +	err := actionConfig.Init(c.restClientGetter, namespace, c.helmDriver, log.Debugf)
必须给RegistryClient赋值，否则会调用helm方法的时候panic

2023-03-17 08:26 UTC, GaoXiaodong commented on pkg/application/helm/action/client.go
> +	err := actionConfig.Init(c.restClientGetter, namespace, c.helmDriver, log.Debugf)
确认这里没问题

2023-03-17 08:46 UTC, GaoXiaodong commented on pkg/application/controller/app/action/install.go
> +		/* provide compatibility with online tke addon apps */
/* provide compatibility with online tke addon apps */
/* compatibility over, above code need to be deleted atfer the online addon apps are migrated */
这段注释中间的不要了，后面我们升级的时候刷下存量，辛苦 @leoryu 帮处理下

2023-03-17 08:47 UTC, GaoXiaodong commented on pkg/application/controller/app/action/upgrade.go
> +		//* provide compatibility with online tke addon apps */
//* provide compatibility with online tke addon apps */
//* compatibility over, above code need to be deleted atfer the online addon apps are migrated */
这两个注释间的也不要了，辛苦 @leoryu 帮处理下

2023-03-20 01:57 UTC, merged