fix(application): app install/upgrade failed when release pending
tkestack/tke pull request #2287
Opened 2023-05-16 10:34 UTC by GaoXiaodong

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2023-05-16 10:42 UTC, huxiaoliang commented on pkg/application/helm/action/install.go
> +		if !strings.Contains(err.Error(), "release: not found") {
please use err.Is() to check error type

2023-05-16 10:45 UTC, huxiaoliang requested changes
please address my comments

2023-05-17 02:27 UTC, GaoXiaodong commented on pkg/application/helm/action/install.go
> +		if !strings.Contains(err.Error(), "release: not found") {
I've dealt with this error

2023-05-18 02:39 UTC, huxiaoliang approved these changes

2023-05-18 07:55 UTC, leoryu approved these changes

2023-05-18 07:55 UTC, DanielXLee approved these changes
/lgtm

2023-05-18 07:55 UTC, merged